name: Create Docker Image + E2E Tests

on:
  pull_request:
  push:
    tags:
    - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      branchTag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CI_ACTOR }}
          password: ${{ secrets.CI_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-tkn-factory:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-tkn-factory
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-packet-forward:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-packet-forward
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-param-authority:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-paramauthority
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-chain-upgrade-authority:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-chain-upgrade
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-globalfee-module:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-globalFee
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}

  test-ics20-bps-fees:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
              
      - name: checkout chain
        uses: actions/checkout@v2
        
      - run: make ictest-ics20-bps-fees
        env:
          BRANCH_CI: ${{needs.build-and-push-image.outputs.branchTag}}
